apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-buildpack-demo-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-buildpack-demo-2
    app.kubernetes.io/part-of: rhtap-buildpack-demo-2
  name: rhtap-buildpack-demo-2
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: rhtap-buildpack-demo-2
status:
  loadBalancer: {}
